SELECT 
HISTORY.CAR_ID

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
JOIN CAR_RENTAL_COMPANY_CAR CAR
ON HISTORY.CAR_ID = CAR.CAR_ID

WHERE MONTH(HISTORY.START_DATE) = 10
AND CAR.CAR_TYPE = '세단'

GROUP BY HISTORY.CAR_ID
ORDER BY HISTORY.CAR_ID DESC;